name: Run Pytest (All Valid Tests)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USER: ${{ secrets.USER }}
      PASSWD: ${{ secrets.PASSWD }}
      DATABASE: ${{ secrets.DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest for selected files
        run: |
          source venv/bin/activate
          PYTHONPATH=src pytest -v \
            tests/test_clean_file.py \
            tests/test_file_validation.py \
            tests/test_csv_to_postgres.py \
            tests/test_refresh_materialized_views.py
