name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 5432
      USER: postgres
      PASSWD: postgres
      DATABASE: test_db

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run pytest if any tests exist
        run: |
          source venv/bin/activate
          if ls tests/test_*.py 2>/dev/null | grep -q .; then
            PYTHONPATH=src pytest -v
          else
            echo "🔸 Nenhum teste ativo no momento."
          fi

